### ISSUE TITLE
Removing the vendor directory

### ISSUE THREAD

**Issue by suntong** [ChimeraCoder/gojson#48]
I personally think that the vendor directory should be removed, because it'll be either duplicated with the current YAML package that we currently have, or out of sync with it. 

Either case, it make little sense to keep it there, IMO. 

Please consider. Thx.

**Comment by ChimeraCoder** [comment]
I'm not sure I understand - where is the duplication happening? Is the issue that you would like to upgrade the vendored version of `gopkg.in/yaml.v2` to a newer version?


Removing the `vendor` director altogether would mean that the application binary itself couldn't be built deterministically from the source repository.

**Comment by suntong** [comment]
The way `gopkg.in` intents to work is to have a stable version as long as possible, shielding the bleeding edged development from the end user. 
`gojson` only has this `gopkg.in/yaml.v2` as the single external dependency, but each of my project would depends on many external dependency go packages. For `gopkg.in/yaml.v2` alone I have a dozen of my projects depending on it. If I have to duplicate `gopkg.in/yaml.v2` as the vendor directory into each and every one of them, that'd be bad management in my view. If I have to duplicate every dependency go packages into every one of my projects, that'd be a total nightmare. 

That being said, I understand the implication of what it means of being production code, so I respect your decision.

**Comment by ChimeraCoder** [comment]
> `gojson` only has this `gopkg.in/yaml.v2` as the single external dependency, but each of my project would depends on many external dependency go packages. For `gopkg.in/yaml.v2` alone I have a dozen of my projects depending on it. If I have to duplicate `gopkg.in/yaml.v2` as the vendor directory into each and every one of them, that'd be bad management in my view. If I have to duplicate every dependency go packages into every one of my projects, that'd be a total nightmare. 

Yeah, I get that it's frustrating to have multiple copies of the same package in your GOPATH. However, tis isn't a decision that I'm making about gojson in a vacuum; it's consistent with the way package management and vendoring is currently being designed to work.

It's possible that Go could or should support deduplication of packages within the `vendor` directories of multiple projects. That's something that would have to be supported by both [dep](https://github.com/golang/dep/) and the Go compiler itself. I have a suspicion that this is unlikely to happen, because the most obvious implementation mechanism would be symbolic links, and the Go project avoids symbolic links because of cross-platform compatibility issues. But, if you feel strongly about this, I'd encourage you to address it with the the authors of dep, since the future of package management in Go is still being actively developed.
